name: spotify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  fpdart: ^2.0.0-dev.3
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  dotted_border: ^2.1.0
  flex_color_picker: ^3.5.1
  file_picker: ^8.1.2
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.40
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.4
  just_audio_background: ^0.0.1-beta.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
